export const API_ROUTES = {
  baseURL: 'https://a578-2a02-d247-2100-6311-6844-c115-f04b-a32e.ngrok-free.app',
  signIn: 'auth/sign-in',
  signUp: 'auth/sign-up',
  confirm: 'auth/confirm',
  email: 'user/email',
  birthdate: 'user/birthdate',
  nickname: 'user/nick-name',
  personalInfo: 'user/personal-info',
  image: 'user/image',
  refresh: 'refresh',
  createPost: 'post',
  getPackages: 'package',
  getVenues: 'place',
  post: '/post',
  users: 'user',
  request: 'request',
  setAvatar: 'user/set-avatar',
  getRequests: 'get-requests',
  takeDecision: 'take-decision',
  auth: 'auth',
  pictures: 'pictures',
};
